export const WS_ORDERS_CONNECTION_START: 'WS_ORDERS_CONNECTION_START' = 'WS_ORDERS_CONNECTION_START';
export const WS_ORDERS_CONNECTION_SUCCESS: 'WS_ORDERS_CONNECTION_SUCCESS' = 'WS_ORDERS_CONNECTION_SUCCESS';
export const WS_ORDERS_CONNECTION_ERROR: 'WS_ORDERS_CONNECTION_ERROR' = 'WS_ORDERS_CONNECTION_ERROR';
export const WS_ORDERS_CONNECTION_CLOSED: 'WS_ORDERS_CONNECTION_CLOSED' = 'WS_ORDERS_CONNECTION_CLOSED';
export const WS_ORDERS_GET_MESSAGE: 'WS_ORDERS_GET_MESSAGE' = 'WS_ORDERS_GET_MESSAGE';
export const WS_ORDERS_SEND_MESSAGE: 'WS_ORDERS_SEND_MESSAGE' = 'WS_ORDERS_SEND_MESSAGE';

export const WS_ORDERS_CONNECT: 'WS_ORDERS_CONNECT' = 'WS_ORDERS_CONNECT';
export const WS_ORDERS_DISCONNECT: 'WS_ORDERS_DISCONNECT' = 'WS_ORDERS_DISCONNECT';

export const orderListActions = {
  wsConnect: WS_ORDERS_CONNECT,
  wsDisconect: WS_ORDERS_DISCONNECT,

  wsSendMessage: WS_ORDERS_SEND_MESSAGE,
  wsConecting: WS_ORDERS_CONNECTION_SUCCESS,
  onOpen: WS_ORDERS_CONNECTION_START,
  onClose: WS_ORDERS_CONNECTION_CLOSED,
  onError: WS_ORDERS_CONNECTION_ERROR,
  onMessage: WS_ORDERS_GET_MESSAGE

}



export const wsOrdersConnect = (url: string) => {
  return {
    type: WS_ORDERS_CONNECT,
    payload: url
  } 
}

export const wsOrderDisconnect = () => {
  return {
    type: WS_ORDERS_DISCONNECT
  } 
}